# AIFocus 配置文件 (用于 aifocus 包自身开发)

project:
  name: "AIFocus"
  type: "typescript"

# 分析路径
analyzePaths:
  - "src/**/*.ts"

# 排除路径
excludePaths:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"

# 输出配置
output:
  reports:
    directory: "./reports"
    focusFile: "focus-report.md"
    reviewFile: "review-report.md"
  docs:
    directory: "docs"

# 规则配置
rules:
  "function.complexityLimit":
    enabled: true
    severity: "warning"
    threshold: 10

  "function.lengthLimit":
    enabled: true
    severity: "warning"
    threshold: 30

  "class.methodCountLimit":
    enabled: true
    severity: "warning"
    threshold: 10

  "class.cohesion":
    enabled: true
    severity: "info"
    threshold: 0.5

  "module.circularDependency":
    enabled: true
    severity: "warning"

# AI配置
ai:
  enabled: true
  provider: "gemini"
  temperature: 0.2
  gemini:
    model: "gemini-1.5-flash"
    # apiKey: "your-api-key-here" # 如需直接配置，请取消注释并替换

debugMode: false
